version: '3.7'
services:
  jenkins:
    build: .
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - "./jenkins:/var/jenkins_home"
